### PR TITLE
Adds reminder functionality for collection.NotionDate

### PR DESCRIPTION
**Pull request by tangjeff0**
This allows reminders to be set programmatically. [Demo](https://twitter.com/tangjeff0/status/1184264669831163904)

### CODE REVIEW

**Comment by jamalex** [comment]
Thanks for the PR, and sorry for the slow response!

Looks like this would also be covered by https://github.com/jamalex/notion-py/pull/49 -- do you (or others) have a strong preference of the class-based vs raw-dict-based approach for this? The library has tended to favor class-based, but this does look to be a simple enough data structure that it may be overkill.

**Comment by offlinehacker** [comment]
Thanks, works for me, using like:

```
row.date = NotionDate(start=today + datetime.timedelta(days=1), reminder={'time': "9:00", 'unit': "day", 'value': 0})
```

**Comment by KShivendu** [comment]
Can you please provide another example for its usage ? The one mentioned here didn't work for me.

**Comment by jamalex** [comment]
Thanks! Has now been merged in via #239, along with some additional fixes.

**Pull request closed without merging**
