### PR TITLE
Fix Invalid Input error for get_collection_view()

### LINKED ISSUE #301: Issues in client.get_collection_view function?
When I try to get one collection I'm getting the following error:
 File "C:\Users\pfser\PycharmProjects\HousesNotion\venv\lib\site-packages\notion\client.py", line 165, in get_collection_view
    collection = self.get_block(
  File "C:\Users\pfser\PycharmProjects\HousesNotion\venv\lib\site-packages\notion\client.py", line 118, in get_block
    block = self.get_record_data("block", block_id, force_refresh=force_refresh)
  File "C:\Users\pfser\PycharmProjects\HousesNotion\venv\lib\site-packages\notion\client.py", line 111, in get_record_data
    return self._store.get(table, id, force_refresh=force_refresh)
  File "C:\Users\pfser\PycharmProjects\HousesNotion\venv\lib\site-packages\notion\store.py", line 184, in get
    self.call_load_page_chunk(id)
  File "C:\Users\pfser\PycharmProjects\HousesNotion\venv\lib\site-packages\notion\store.py", line 286, in call_load_page_chunk
    recordmap = self._client.post("loadPageChunk", data).json()["recordMap"]
  File "C:\Users\pfser\PycharmProjects\HousesNotion\venv\lib\site-packages\notion\client.py", line 209, in post
    raise HTTPError(
requests.exceptions.HTTPError: Invalid input.

Someone is getting the same error or there are any updates in the lib?

### PR DESCRIPTION
**Pull request by yashgorana**
Fixes #301

- loadPageChunk API requires Page ID as an object
- limit needs to be <= 100

### CODE REVIEW

**Comment by Shrikey** [comment]
I also encountered this error; please merge it.

**Comment by yashgorana** [comment]
@jamalex This is a critical fix. Can you please merge this change?

**Comment by Shrikey** [comment]
@jamalex Please merge this change.

**Review by rimonhanna — APPROVED** [review]

**Comment by dbarrundiag** [comment]
+1

**Comment by jamalex** [comment]
Looks like this should be addressed by https://github.com/jamalex/notion-py/pull/352 which was just merged. Thanks!

**Pull request closed without merging**
