### PR TITLE
Add minimum Python version note

### LINKED ISSUE #25: Instantiation of NotionClient fails
After trying to follow the basic tutorial in the README, I encountered an error.

```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\notion\store.py", line 111, in _load_cache
    with open(self._get_cache_path(attr)) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\.notion-py\\cache\\edf90714b95fc442ac97965a8e2fb37795a647ed342bd73df657bcd3c6a016ea_values.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\index.py", line 3, in <module>
    client = NotionClient(token_v2='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
  File "C:\Python34\lib\site-packages\notion\client.py", line 33, in __init__
    self._store = RecordStore(self, cache_key=cache_key)
  File "C:\Python34\lib\site-packages\notion\store.py", line 82, in __init__
    self._load_cache()
  File "C:\Python34\lib\site-packages\notion\store.py", line 117, in _load_cache
    except (FileNotFoundError, json.JSONDecodeError):
AttributeError: 'module' object has no attribute 'JSONDecodeError'
```

Any ideas as to what could be causing this?

### PR DESCRIPTION
**Pull request by weaversam8**

### CODE REVIEW

**Comment by weaversam8** [comment]
Okay this pull request should resolve the issues in #25

**Comment by jamalex** [comment]
Thanks! I'd like to have 3.4 compatibility, though, so I've made the fix that should enable that in https://github.com/jamalex/notion-py/commit/48c0fd686ddb1055861f973653d73f88cd82b117

**Comment by jamalex** [comment]
Actually, looks as if Python 3.4 is [past end-of-life](https://www.python.org/dev/peps/pep-0429/), so it probably doesn't make sense to maintain support (in testing further, I was having issues with IPython itself with 3.4, and that's how I saw the EOL note).

I've released 0.0.22 with 3.4 support, and will now bump to 0.0.23 and remove support, adding your note and a version change in setup.py

Thanks!

**Comment by jamalex** [comment]
See https://github.com/jamalex/notion-py/commit/ef0c5e02bd4ae5ad8d34c6c56e4e842b15aeaa01

0.0.23 has been released. Thanks again!

**Pull request closed without merging**
