### PR TITLE
Change queryCollection request payload and response parsing

### PR DESCRIPTION
**Pull request by wsykala**
#350 

This change works for table views, but it might not work for other types (for example board view).

### CODE REVIEW

**Comment by pavelapekhtin** [comment]
Did not seem to fix it for me, or am i doing it wrong?

merging it like this
`pip install git+https://github.com/jamalex/notion-py.git@refs/pull/352/merge`

and it fails at `get_rows()` with `raise HTTPError(
requests.exceptions.HTTPError: Invalid input.`

`
client = NotionClient(token_v2=v2_token)
page = client.get_block(page_url)
cv = client.get_collection_view(page_url)

for row in cv.collection.get_rows(search='Q'):
....
`

**Comment by felipehlvo** [comment]
It also worked in my board view!

**Comment by wsykala** [comment]
Might fix some of the issues mentioned in #351

**Comment by alexattia** [comment]
Working for me! Would be great if it could be merged

**Review by alexattia — APPROVED** [review]

**Comment by thomashirtz** [comment]
When will it be merge ? It is quite annoying to have buggy notion-py out of the box ..

**Comment by ashutoshsaboo** [comment]
+1, can you please merge these changes @wsykala given now the PR has been approved as well by both reviewers?

**Comment by wsykala** [comment]
@ashutoshsaboo I would love to do it but I don't have write access to the main repository so I can't merge it

**Comment by ashutoshsaboo** [comment]
cc'ing repo owner, @jamalex could you please help get this PR merged? notion-py seems to be broken rn without this fix..

**Comment by srepollock** [comment]
Is there a timeline for when this will be merged in?

**Comment by wsykala** [comment]
Updated to address https://github.com/jamalex/notion-py/issues/365#issuecomment-1041977974

**Comment by laserroger** [comment]
Hi, under this case how can we use filters in `cv.build_query()`?

**Comment by laserroger** [comment]
Now I can only do the filtering via the "integration" method suggested by the [notion official API](https://developers.notion.com/reference/post-database-query). The v2 token doesn't work for this method even after formatting the filter properly and embedding it into the store.py's `data` in the `call_query_collection `.

**Comment by jamalex** [comment]
Thanks all, and sorry that I haven't been able to attend to this project due to capacity. Trying to get some of the key PRs like this merged in now to get the base version functional again.

**Pull request merged**
